### PR TITLE
Add option to copy to clipboard

### PR DESCRIPTION
**Pull request by spyoungtech**
This is something that helped me, since the string is too long to copy cleanly from a terminal window.

### CODE REVIEW

**Comment by mandeep** [comment]
Thanks, this is a great addition. Is it possible to add a test for this?

**Comment by spyoungtech** [comment]
Definitely. I made a test for this, which runs fine on Windows, bringing coverage back to 100. Hopefully trusty has the required packages by default.

**Comment by spyoungtech** [comment]
Looks like trusty does not have what pyperclip needs by default. :disappointed: 

> Pyperclip could not find a copy/paste mechanism for your system. For more information, please visit https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error

According to the docs, one of the following mechanisms for clipboard needs to be installed.

- `sudo apt-get install xsel` to install the xsel utility.
- `sudo apt-get install xclip` to install the xclip utility.
- `pip install gtk` to install the gtk Python 
- `pip install PyQt4` to install the PyQt4 Python module.

Looking at the [travis build for clipr](https://github.com/mdlincoln/clipr) they use `xsel` so I'll give that a shot and see.

**Comment by spyoungtech** [comment]
Well. xsel installs fine, but Pyperclip still doesn't seem to recognize that it is available. I'll dig deeper into this later today when I can take a closer look. 

Thanks.

**Comment by mandeep** [comment]
Thanks, I'll take a look too and see if I can come up with a solution.

**Comment by spyoungtech** [comment]
It looks like the logic in pyperclip won't even try to determine if an option is available if a screen is not available. This is because these packages (tested xclip and xsel) require a screen to be available.

I was able to resolve this by using xvfb, which is available in the travis trusty build by default.

**Comment by spyoungtech** [comment]
I had wrote the test based off of [test_password_output]( https://github.com/mandeep/Travis-Encrypt/blob/master/tests/test_cli.py#L21-L28). 

`clip_contents = pyperclip.paste()` does what you might think it does -- it's the contents of the clipboard (a string, `''` if there is no clipboard contents).
`assert clip_contents` makes sure that there was ANY content in the clipboard (same as `assert bool(clip_contents)`).
`assert base64.b64decode(clip_contents)` I assume is just a loose check of validity, which I merely copied from the other tests.

I think `assert clip_contents == expected_password` is a good idea. If I'm using this thing right `expected_password` should be as [found here](https://gist.github.com/spyoungtech/003a0a5d33a160bd0bdbd188377c25bf). AFAICT, this doesn't exist elsewhere in the repo/tests. So we could add that as a file and read it for the test, I suppose.

**Comment by mandeep** [comment]
I think this test is good. One way to test the paste is by creating a unit test that creates a secure password and see if pyperclip will copy and paste it properly.

**Comment by spyoungtech** [comment]
This is what I came up with. I added a test that asserts the contents of the clipboard are as expected. In this case, I mock `encrypt_key` to return an expected value and test that the clipboard contains that expected value after running the cli.

Hope that makes sense.

**Comment by mandeep** [comment]
This looks awesome, great work here! Thanks for taking the time to add this feature and related tests!

**Pull request merged**
